routes/web.php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});

Route::get('/dashboard', function () {
    return Inertia::render('Dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/usuario', [UserController::class,'index'])->name('users');

Route::get('/usuario/crear', [UserController::class,'create'])->name('users.create');
Route::post('/usuario/store', [UserController::class,'store'])->name('users.store');

Route::get('/usuario/editar/{id}', [UserController::class,'edit'])->name('users.edit');
Route::post('/usuario/modificar/{id}', [UserController::class,'update'])->name('users.update');

Route::get('/usuario/eliminar/{id}', [UserController::class, 'destroy'])->name('users.destroy');



Route::get('/rol', [RoleController::class,'index'])->name('roles');

Route::get('/rol/crear', [RoleController::class,'create'])->name('roles.create');
Route::post('/rol/store', [RoleController::class,'store'])->name('roles.store');

Route::get('/rol/editar/{id}', [RoleController::class,'edit'])->name('roles.edit');
Route::post('/rol/modificar/{id}', [RoleController::class,'update'])->name('roles.update');

Route::get('/rol/eliminar/{id}', [RoleController::class,'destroy'])->name('roles.destroy');

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles(){
        return $this->belongsToMany(Role::class);
    }

    public function image(){    
        return $this->morphOne(Image::class, 'imageable');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Models\User;
use App\Models\Role;
use App\Models\Image;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Throwable;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $users = User::orderBy('id','desc')->paginate(5);
       //dd($users);
       return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::orderBy('name','desc')->get();
        $roles = Role::orderBy('name')->get();
        return view('admin.user.create', ['users' => $users, 'roles' => $roles]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStoreRequest $request)
    {
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $request->password,
        ]);
        
        //$user->roles()->sync($request->input('roles', []));

        if($request->file('image')){
            $url = Storage::put('images', $request->file('image'));
            $user->image()->create([
                'url' => $url
            ]);
        }
        if($request->roles){
            $user->roles()->attach($request->roles);
        }
        if($user){
            return redirect('usuario')->with('success', 'Nuevo usuario creado con exito');
        }
        else{
            return redirect('usuario/crear')->with('error', 'Error al crear al usuario');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::orderBy('name','desc')->get();
        return view('admin.user.edit', ['user' => $user, 'roles' => $roles]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
            $user = User::findOrFail($id);
            $user->update($request->all());
            //$user->update($request->validated());
            if($request->file('image')){
                $url = Storage::put('images', $request->file('image'));

                if($user->image){
                    Storage::delete($user->image->url);
                    $user->image->update([
                        'url' => $url
                    ]);
                }
                else{
                    $user->image()->create([
                        'url' => $url
                    ]);
                }
            }

            if($request->roles){
                $user->roles()->attach($request->roles);
            }
            
            return redirect('usuario')->with('success', 'Usuario actualizado exitosamente');
        }
        catch(Throwable $e){
            return redirect('usuario')->with('error','Error al actualizar al usuario'.$e);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $result = $user->delete();

        if($user->image){
            Storage::delete($user->image->url);
            $user->image->delete();
        }

        if($result){
            return redirect('usuario')->with('success', 'Usuario eliminado exitosamente');
        }
        else{
            return redirect('usuario')->with('error', 'Error al eliminar al usuario');
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/user/create.blade.php
<x-app-layout>
    <x-slot name="header">
    <div class="flex items-center justify-between"> 
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Add user') }}                            
        </h2>   
        <a href="{{ route('users') }}" class="hover:bg-light-blue-200 hover:text-light-blue-800 group flex items-center rounded-md bg-light-blue-100 text-light-blue-600 text-sm font-medium px-4 py-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd" />
            </svg>      
            &nbsp;  
            {{ __('Back') }}        
        </a>        
    </div>          
    </x-slot>       

  <div class="py-12"> 
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="flex flex-col">
                    <div class="mt-5 md:mt-0 md:col-span-2">
                        <form method="POST" action="{{ route('users.store')}}" enctype="multipart/form-data">
                        @csrf   
                          <div class="shadow overflow-hidden sm:rounded-md">
                            <div class="px-4 py-5 bg-white sm:p-6"> 
                              <div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-4">        
                                <div class="px-4 py-5 bg-white sm:p-6">
                                  <label for="roles" class="block text-sm font-medium text-gray-700">Rol</label>
                                  <select name="roles[]" id="roles" multiple="multiple" class="form-multiselect block rounded-md shadow-sm mt-1 block w-full">
                                    @foreach($roles as $role)
                                    <option value="{{ $role->id }}">
                                      {{ $role->name }}
                                    </option>
                                    @endforeach
                                  </selesct>
                                  @error('roles')
                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                  @enderror 
                                </div> 
                                <br>
                                <div class="px-4 py-5 bg-white sm:p-6"></div>
                                <th></th>
                                <br>
                                <div class="px-4 py-5 bg-white sm:p-6"> 
                                <br>      
                                  <label for="name" class="block text-sm font-medium text-gray-700">Nombre</label>
                                  <input type="text" name="name" id="name" autocomplete="name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                  @error('name')
                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                  @enderror
                                </div> 
                                <div class="px-4 py-5 bg-white sm:p-6">       
                                  <label for="email" class="block text-sm font-medium text-gray-700">Correo electronico</label>
                                  <input type="text" name="email" id="email" autocomplete="email" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                  @error('email')
                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                  @enderror
                                </div>
                                <div class="px-4 py-5 bg-white sm:p-6">       
                                  <label for="password" class="block text-sm font-medium text-gray-700">Contraseña</label>
                                  <input type="password" name="password" id="password" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                  @error('password')
                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                  @enderror
                                </div>                    
                                <div class="px-4 py-5 bg-white sm:p-6">
                                  <label for="image" class="block text-sm font-medium text-gray-700">Imagen</label>
                                  <input type="file" name="image" id="image" class="mt-1 focus:ring-indigo-500 block w-full">   
                                </div>
                                @error('image')
                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                @enderror
                                
                                             
                            </div>        
                            <div class="px-4 py-3 bg-white text-right sm:px-6"> 
                              <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                {{ __('Save') }}    
                              </button>
                            </div>      
                          </div>
                        </form>
                    </div>
                </div>                
            </div>
        </div>      
    </div>                    
    
    
</x-app-layout>

resources/views/admin/user/edit.blade.php
<x-app-layout>
    <x-slot name="header">
    <div class="flex items-center justify-between"> 
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit user') }}                            
        </h2>   
        <a href="{{ route('users') }}" class="hover:bg-light-blue-200 hover:text-light-blue-800 group flex items-center rounded-md bg-light-blue-100 text-light-blue-600 text-sm font-medium px-4 py-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd" />
            </svg>      
            &nbsp;  
            {{ __('Back') }}        
        </a>        
    </div>          
    </x-slot>       

    <div class="py-12"> 
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="flex flex-col">
                    <div class="mt-5 md:mt-0 md:col-span-2">
                        <form method="POST" action="{{ route('users.update', $user->id) }}" enctype="multipart/form-data">      
                          @csrf
                          <div class="shadow overflow-hidden sm:rounded-md">
                            <div class="px-4 py-5 bg-white sm:p-6">
                              <div class="grid grid-cols-6 gap-6">   
                                <div class="col-span-12 sm:col-span-12"> 
                                  <label for="name" class="block text-sm font-medium text-gray-700">Nombre</label>
                                  <input type="text" name="name" value="{{ $user->name }}" id="name" autocomplete="name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                </div> 
                                <div class="col-span-12 sm:col-span-12"> 
                                  <label for="email" class="block text-sm font-medium text-gray-700">Correo electronico</label>
                                  <input type="text" name="email" value="{{ $user->email }}" id="email" autocomplete="email" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                </div>
                                <div class="col-span-12 sm:col-span-12"> 
                                  <label for="password" class="block text-sm font-medium text-gray-700">Contraseña</label>
                                  <input type="password" name="password" value="{{ $user->password }}" id="password" autocomplete="password" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                </div>

                                <div class="col-span-12 sm:col-span-12">
                                  @if ($user->image)
                                    <img src="{{ Storage::url($user->image->url) }}"  width="500" height="500">
                                  @else
                                    Sin imagen
                                  @endif
                                </div>

                                <div class="col-span-12 sm:col-span-12">
                                  <label for="image" class="block text-sm font-medium text-gray-700">Imagen</label>
                                  <input type="file" name="image" id="image" class="mt-1 focus:ring-indigo-500 block w-full">   
                                </div>

                                <div class="px-4 py-5 bg-white sm:p-6">
                                  <label for="roles" class="block text-sm font-medium text-gray-700">Rol</label>
                                  <select name="roles[]" id="roles">
                                    @foreach($roles as $role)
                                    <option value="{{ $role->id }}"> 
                                      {{ $role->name }}
                                    </option>
                                    @endforeach
                                  </select>
                                </div>

                            </div>      
                            <div class="px-4 py-3 bg-white text-right sm:px-6"> 
                            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                {{ __('Update') }}    
                              </button> 
                            </div>      
                          </div>
                        </form>
                    </div>
                </div>                
            </div>
        </div>      
    </div>           
    
    
</x-app-layout>

resources/views/admin/user/index.blade.php
<x-app-layout>
    <x-slot name="header">
    <div class="flex items-center justify-between"> 
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users list') }}                       
        </h2>
        <a type="button" href="{{route('users.create')}}" class="hover:bg-light-blue-200 hover:text-light-blue-800 group flex items-center rounded-md bg-light-blue-100 text-light-blue-600 text-sm font-medium px-4 py-2">    
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
              </svg>    
            {{ __('Add') }}                 
        </a>      
    </div>  
    </x-slot>   

    <div class="py-12"> 
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">      
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">      
                <div class="flex flex-col">
                    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                                <tr>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Nombre
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Correo electronico
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Fecha creación
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Imagen
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Rol
                                </th>                          
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Acciones
                                </th>
                                </tr>   
                            </thead>    
                            <tbody class="bg-white divide-y divide-gray-200">
                            @foreach ($users as $user)
                                <tr>     
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {{ $user->name }}                
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {{ $user->email }}                
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {{ $user->created_at }}    
                                </td>
                                <td class="px-6 py-4">
                                    @if ($user->image)
                                    <img src="{{ Storage::url($user->image->url) }}">
                                    @else
                                    Sin imagen
                                    @endif
                                </td> 
                                <td class="px-6 py-4">
                                    @foreach ($user->roles as $role)
                                    <span>
                                        {{ $role->name }}
                                    </span>
                                    @endforeach
                                </td>       
                                <td class="px-6 py-4 whitespace-nowrap">            
                                    <a type="button" href="{{route('users.edit', $user->id)}}" class="inline-flex items-center px-4 py-2 border border-current rounded-md shadow-sm text-sm font-medium text-white bg-blue-500 hover:bg-blue-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Editar</a>       
                                    <a type="button" href="{{route('users.destroy', $user->id)}}" class="inline-flex items-center px-4 py-2 border border-current rounded-md shadow-sm text-sm font-medium text-white bg-red-500 hover:bg-red-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Eliminar</a>
                                </td>               
                                </tr>                                               
                            @endforeach
                            </tbody>
                            </table>
                        </div>
                        </div>
                    </div>
                </div>
                <div class="flex flex-col py-4">        
                    {{ $users->links() }}                       
                </div>                
            </div>
        </div>      
    </div>      
</x-app-layout>